controllers:
    resource: ../src/Controller/
    type: attribute

# Přihlašovací stránka
app_login:
    path: /login
    controller: App\Controller\LoginController::index

# Odhlášení
app_logout:
    path: /logout
    methods: GET


# Seznam studentů
app_student_index:
    path: /student
    controller: App\Controller\StudentController::index
